### ISSUE TITLE
MOCK iShowcase - Instructor review 

### ISSUE THREAD

**Issue by annahoju** [INFO-526-FA24/project-2-datavizionaries#5]
Good color 
correlation matrix - triangle 
gender cut off label.
Reconsider the Distribution of mental health treatment global visual to include some sort of proportion. 
Include the source of the data. 
Fix the timeline x-axis

**Comment by srikrish2812** [comment]
Hello Professor Anna Leach,

Thank you for the feedback. We have updated the poster as per your feedback.
